name: CI

on:
  push:
    branches: [ main ]

jobs:
  ci:
    
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Install minimal stable with clippy and rustfmt
        uses: acrions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Rust format
        run: rustfmt src/*

      - name: Clippy
        run: cargo clippy

      - name: Run test
        run: cargo test --verbose

      - name: Build
        run: cargo build --verbose

